force-app/main/default/objects/Guild__c/Guild__c.object-meta.xml
<CustomObject>
    <label>Guild</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guilds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/Hero__c.object-meta.xml
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Heros</relationshipLabel>
    <relationshipName>Heros</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hero__c/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guild</label>
    <referenceTo>Guild__c</referenceTo>
    <relationshipLabel>Heros</relationshipLabel>
    <relationshipName>Heros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mission_Assignment__c/Mission_Assignment__c.object-meta.xml
<CustomObject>
    <label>Mission Assigment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mission Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mission_Assignment__c/fields/Hero__c.field-meta.xml
<CustomField>
    <fullName>Hero__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hero</label>
    <referenceTo>Hero__c</referenceTo>
    <relationshipLabel>Mission Assignments</relationshipLabel>
    <relationshipName>Mission_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mission_Assignment__c/fields/Mission__c.field-meta.xml
<CustomField>
    <fullName>Mission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mission</label>
    <referenceTo>Superhero_Mission__c</referenceTo>
    <relationshipLabel>Mission Assignments</relationshipLabel>
    <relationshipName>Mission_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Superhero_Mission__c/Superhero_Mission__c.object-meta.xml
<CustomObject>
    <label>Superhero Mission</label>
    <nameField>
        <displayFormat>SM-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Superhero Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/TestDataService.cls
@isTest
public class TestDataService {
  // create Account
  public static Account createAccount(String name) {
    Account portalAccount = new Account();
    portalAccount.Name = name;
    return portalAccount;
  }

  // create Contact
  public static Contact createContact(
    String lastName,
    String email,
    Id accountId
  ) {
    Contact portalContact = new contact();
    portalContact.LastName = lastName;
    portalContact.Email = email;
    portalContact.AccountId = accountId;
    return portalContact;
  }

  // create Contact
  public static Contact createContact(String lastName) {
    Contact contact = new Contact();
    contact.LastName = lastName;
    return contact;
  }

  // create Hero
  public static Hero__c createHero(String name, Id contactId, Id guildId) {
    Hero__c hero = new Hero__c();
    hero.Name = name;
    hero.Contact__c = contactId;
    hero.Guild__c = guildId;
    return hero;
  }

  // create Guild
  public static Guild__c createGuild(String name) {
    Guild__c guild = new Guild__c();
    guild.Name = name;
    return guild;
  }

  // create Superhero Mission
  public static Superhero_Mission__c createSuperheroMission(
    String subject,
    Id guildId
  ) {
    Superhero_Mission__c superheroMission = new Superhero_Mission__c();
    superheroMission.Guild__c = guildId;
    superheroMission.Subject__c = subject;
    superheroMission.Details__c = subject;
    return superheroMission;
  }

  // create Mission Assignment
  public static Mission_Assignment__c createMissionAssignment(
    Id heroId,
    Id missionId
  ) {
    Mission_Assignment__c missionAssignment = new Mission_Assignment__c();
    missionAssignment.Hero__c = heroId;
    missionAssignment.Mission__c = missionId;
    return missionAssignment;
  }

  // create Commuinity User
  public static User createCommunityUser(
    String contactId,
    String profileId,
    String firstName,
    String lastName
  ) {
    User user = new User();
    user.ProfileId = profileId;
    user.FirstName = firstName + String.valueOf(System.today());
    user.LastName = lastName;
    user.Email = 'test@test.com';
    user.Username = String.valueOf(System.today()) + '@gmail.com.test';
    user.Alias = 'alias';
    user.TimeZoneSidKey = 'America/Los_Angeles';
    user.LanguageLocaleKey = 'en_US';
    user.LocaleSidKey = 'en_US';
    user.EmailEncodingKey = 'UTF-8';
    user.ContactId = contactId;

    return user;
  }
}