force-app/main/default/objects/Guild__c/Guild__c.object-meta.xml
<CustomObject>
    <label>Guild</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guilds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/Hero__c.object-meta.xml
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guild</label>
    <referenceTo>Guild__c</referenceTo>
    <relationshipLabel>Heros</relationshipLabel>
    <relationshipName>Heros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mission_Assignment__c/Mission_Assignment__c.object-meta.xml
<CustomObject>
    <label>Mission Assigment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mission Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mission_Assignment__c/fields/Hero__c.field-meta.xml
<CustomField>
    <fullName>Hero__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hero</label>
    <referenceTo>Hero__c</referenceTo>
    <relationshipLabel>Mission Assignments</relationshipLabel>
    <relationshipName>Mission_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mission_Assignment__c/fields/Mission__c.field-meta.xml
<CustomField>
    <fullName>Mission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mission</label>
    <referenceTo>Superhero_Mission__c</referenceTo>
    <relationshipLabel>Mission Assignments</relationshipLabel>
    <relationshipName>Mission_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mission_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Superhero_Mission__c/Superhero_Mission__c.object-meta.xml
<CustomObject>
    <label>Superhero Mission</label>
    <nameField>
        <displayFormat>SM-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Superhero Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/MissionAssignmentTriggerHandlerTest.cls
@IsTest
private class MissionAssignmentTriggerHandlerTest {
  @testSetup
  static void setup() {
    // Create test data
    Account account = TestDataService.createAccount('Test Account');
    insert account;

    Contact contact = TestDataService.createContact(
      'Test Contact',
      'test@gmail.com',
      account.Id
    );
    insert contact;

    Guild__c guild = TestDataService.createGuild('Test guild');
    insert guild;

    Hero__c hero = TestDataService.createHero(
      'Test hero',
      contact.Id,
      guild.Id
    );
    Hero__c hero2 = TestDataService.createHero(
      'Test hero2',
      contact.Id,
      guild.Id
    );
    insert new List<Hero__c>{ hero, hero2 };

    Superhero_Mission__c superheroMission = TestDataService.createSuperheroMission(
      'Test subject',
      guild.Id
    );
    insert superheroMission;

    Mission_Assignment__c missionAssignment = TestDataService.createMissionAssignment(
      hero.Id,
      superheroMission.Id
    );
    Mission_Assignment__c missionAssignment2 = TestDataService.createMissionAssignment(
      hero2.Id,
      superheroMission.Id
    );
    insert new List<Mission_Assignment__c>{
      missionAssignment,
      missionAssignment2
    };
  }

  // Check functionality of setting 'Failed' status
  @IsTest
  static void setFailedStatusTest() {
    Superhero_Mission__c superheroMission = [
      SELECT Id
      FROM Superhero_Mission__c
      LIMIT 1
    ];
    Mission_Assignment__c missionAssignmentToUpdate = [
      SELECT Id, Status__c
      FROM Mission_Assignment__c
      LIMIT 1
    ];
    Test.startTest();
    missionAssignmentToUpdate.Status__c = Constants.MISSION_ASSIGNMENT_STATUS_COMPLETED;
    update missionAssignmentToUpdate;
    Test.stopTest();
    Mission_Assignment__c missionAssignment = [
      SELECT Id, Status__c
      FROM Mission_Assignment__c
      WHERE
        Mission__c = :superheroMission.Id
        AND Id != :missionAssignmentToUpdate.Id
    ];

    System.assert(
      missionAssignment.Status__c == Constants.MISSION_ASSIGNMENT_STATUS_FAILED,
      'Mission Assignment Status should be updated to Failed'
    );
  }

  // Test functionality of sending emails
  @IsTest
  static void sendEmailToMissionCreatorTest() {
    Superhero_Mission__c superheroMission = [
      SELECT Id
      FROM Superhero_Mission__c
      LIMIT 1
    ];
    Mission_Assignment__c missionAssignmentToUpdate = [
      SELECT Id, Status__c
      FROM Mission_Assignment__c
      LIMIT 1
    ];
    missionAssignmentToUpdate.Status__c = Constants.MISSION_ASSIGNMENT_STATUS_COMPLETED;

    Boolean isException = false;

    Test.startTest();
    try {
      update missionAssignmentToUpdate;
    } catch (Exception e) {
      isException = true;
    }
    Test.stopTest();

    // Query the EmailMessage records
    List<EmailMessage> sentEmails = [SELECT Id, Status FROM EmailMessage];

    // Assert that emails were sent
    System.assertNotEquals(
      0,
      sentEmails.size(),
      'Email messages should have been sent'
    );

    for (EmailMessage email : sentEmails) {
      // Verify that the email has a 'Sent' status
      System.assertEquals(
        '3',
        email.Status,
        'Email should have a "Sent" status'
      );
    }

    System.assert(
      !isException,
      'Email message should be sent without exceptions'
    );
  }
}