force-app/main/default/objects/Guild__c/Guild__c.object-meta.xml
<CustomObject>
    <label>Guild</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guilds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/Hero__c.object-meta.xml
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Heros</relationshipLabel>
    <relationshipName>Heros</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hero__c/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guild</label>
    <referenceTo>Guild__c</referenceTo>
    <relationshipLabel>Heros</relationshipLabel>
    <relationshipName>Heros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SuperheroMissionBatch.cls
public class SuperheroMissionBatch implements Database.Batchable<SObject>, Database.Stateful {
  // Store Superhero Mission IDs
  public List<Id> missionGuildIds = new List<Id>();

  public Database.QueryLocator start(Database.BatchableContext context) {
    // query to retrieve the Heros using the stored missionGuildIds.
    System.debug('missionGuildIds: ' + missionGuildIds);
    String query = 'SELECT Contact__r.Email, Guild__r.Id FROM Hero__c WHERE Guild__r.Id IN :missionGuildIds';
    return Database.getQueryLocator(query);
  }

  public void execute(Database.BatchableContext context, List<Hero__c> scope) {
    List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
    for (Hero__c member : scope) {
      System.debug('email: ' + member.Contact__r.Email);
      // Create and add email messages to the list.
      Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
      email.setToAddresses(new List<String>{ member.Contact__r.Email });
      email.setSubject('New Superhero Mission');
      email.setPlainTextBody('A new mission has been assigned to your guild.');
      emails.add(email);
    }

    // Send the collected email messages.
    Messaging.SendEmailResult[] emailResults = Messaging.sendEmail(emails);
  }

  public void finish(Database.BatchableContext context) {
  }
}