force-app/main/default/objects/Guild__c/Guild__c.object-meta.xml
<CustomObject>
    <label>Guild</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guilds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/Hero__c.object-meta.xml
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guild</label>
    <referenceTo>Guild__c</referenceTo>
    <relationshipLabel>Heros</relationshipLabel>
    <relationshipName>Heros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Superhero_Mission__c/Superhero_Mission__c.object-meta.xml
<CustomObject>
    <label>Superhero Mission</label>
    <nameField>
        <displayFormat>SM-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Superhero Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/AllMissionsControllerTest.cls
@IsTest
private class AllMissionsControllerTest {
  @testSetup
  static void setup() {
    // create data for tests
    Account account = TestDataService.createAccount('Test Account');
    insert account;

    Contact contact = TestDataService.createContact(
      'Test Contact',
      'test@gmail.com',
      account.Id
    );
    insert contact;

    Id profileId = [
      SELECT Id
      FROM Profile
      WHERE Name = 'Superhero Community User'
    ]
    .Id;
    User communityUser = TestDataService.createCommunityUser(
      contact.Id,
      profileId,
      'Test',
      'SuperheroUser'
    );
    insert communityUser;

    Guild__c guild = TestDataService.createGuild('Test guild');
    insert guild;

    Hero__c hero = TestDataService.createHero(
      'Test hero',
      contact.Id,
      guild.Id
    );
    insert hero;

    Superhero_Mission__c superheroMission = TestDataService.createSuperheroMission(
      'Test subject',
      guild.Id
    );
    Superhero_Mission__c publicSuperheroMission = TestDataService.createSuperheroMission(
      'Test subject2',
      guild.Id
    );
    insert new List<Superhero_Mission__c>{
      superheroMission,
      publicSuperheroMission
    };
  }

  // Test Controller method retrieving all accessible missions
  @IsTest
  static void getAllMissionsTest() {
    User user = [SELECT Id FROM User WHERE LastName = 'SuperheroUser'];
    System.runAs(user) {
      List<AllMissionsController.MissionWrapper> superheroMissions = AllMissionsController.getAllMissions();
      System.assert(
        superheroMissions.size() == 2,
        'Should be found two missions'
      );
    }
  }
}